version: '3.0'
services:
  app:
    build: .
    volumes:
      - .:/home/bart
  jupyter:
    image: 'jupyter/scipy-notebook'
    ports:
      - '8888:8888'
    volumes:
      - .:/home/bart
    working_dir: /home/bart
